pipeline{
     agent any
         
         stages{
               stage('BUILD STAGE'){
                     
                     steps{
                     
                     withMaven(maven: 'maven_3_5_0')
                            sh 'mvn clean compile'	
                     
                     }
                   
               }
               
               stage('DEPLOY'){
               
                   steps{
                    withCredentials([[$class           : 'UsernamePasswordMultiBinding',
                                      credentialsID    : 'PCF_LOGIN',
                                      usernameVariable :  'USERNAME',
                                      passwordVariable :  'PASSWORD ']])  
                   
                   }
               
               
               
               }
         
         }
}
